-- MySQL Script generated by MySQL Workbench
-- Fri May  5 13:25:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Yelp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Yelp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Yelp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Yelp` ;

-- -----------------------------------------------------
-- Table `Yelp`.`attributes_business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`attributes_business` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`attributes_business` (
  `business_id` VARCHAR(50) NULL DEFAULT NULL,
  `ByAppointmentOnly` TEXT NULL DEFAULT NULL,
  `BusinessAcceptsCreditCards` TEXT NULL DEFAULT NULL,
  `BikeParking` TEXT NULL DEFAULT NULL,
  `RestaurantsPriceRange2` TEXT NULL DEFAULT NULL,
  `CoatCheck` TEXT NULL DEFAULT NULL,
  `RestaurantsTakeOut` TEXT NULL DEFAULT NULL,
  `RestaurantsDelivery` TEXT NULL DEFAULT NULL,
  `Caters` TEXT NULL DEFAULT NULL,
  `WiFi` TEXT NULL DEFAULT NULL,
  `BusinessParking` TEXT NULL DEFAULT NULL,
  `WheelchairAccessible` TEXT NULL DEFAULT NULL,
  `HappyHour` TEXT NULL DEFAULT NULL,
  `OutdoorSeating` TEXT NULL DEFAULT NULL,
  `HasTV` TEXT NULL DEFAULT NULL,
  `RestaurantsReservations` TEXT NULL DEFAULT NULL,
  `DogsAllowed` TEXT NULL DEFAULT NULL,
  `Alcohol` TEXT NULL DEFAULT NULL,
  `GoodForKids` TEXT NULL DEFAULT NULL,
  `RestaurantsAttire` TEXT NULL DEFAULT NULL,
  `Ambience` TEXT NULL DEFAULT NULL,
  `RestaurantsTableService` TEXT NULL DEFAULT NULL,
  `RestaurantsGoodForGroups` TEXT NULL DEFAULT NULL,
  `DriveThru` TEXT NULL DEFAULT NULL,
  `NoiseLevel` TEXT NULL DEFAULT NULL,
  `GoodForMeal` TEXT NULL DEFAULT NULL,
  `BusinessAcceptsBitcoin` TEXT NULL DEFAULT NULL,
  `Smoking` TEXT NULL DEFAULT NULL,
  `Music` TEXT NULL DEFAULT NULL,
  `GoodForDancing` TEXT NULL DEFAULT NULL,
  `AcceptsInsurance` TEXT NULL DEFAULT NULL,
  `BestNights` TEXT NULL DEFAULT NULL,
  `BYOB` TEXT NULL DEFAULT NULL,
  `Corkage` TEXT NULL DEFAULT NULL,
  `BYOBCorkage` TEXT NULL DEFAULT NULL,
  `HairSpecializesIn` TEXT NULL DEFAULT NULL,
  `Open24Hours` TEXT NULL DEFAULT NULL,
  `RestaurantsCounterService` TEXT NULL DEFAULT NULL,
  `AgesAllowed` TEXT NULL DEFAULT NULL,
  `DietaryRestrictions` TEXT NULL DEFAULT NULL,
  `attributes_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`attributes_id`),
  INDEX `attributes_business_business_id_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `attributes_business_business_id`
    FOREIGN KEY (`business_id`)
    REFERENCES `Yelp`.`business_data` (`business_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 137361
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Yelp`.`business_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`business_data` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`business_data` (
  `business_id` VARCHAR(50) NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `city` TEXT NULL DEFAULT NULL,
  `state` TEXT NULL DEFAULT NULL,
  `postal_code` TEXT NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `stars` DOUBLE NULL DEFAULT NULL,
  `review_count` BIGINT NULL DEFAULT NULL,
  `is_open` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`business_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Yelp`.`categories_business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`categories_business` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`categories_business` (
  `business_id` VARCHAR(50) NULL DEFAULT NULL,
  `categories` TEXT NULL DEFAULT NULL,
  `categories_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`categories_id`),
  INDEX `categories_business_business_id_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `categories_business_business_id`
    FOREIGN KEY (`business_id`)
    REFERENCES `Yelp`.`business_data` (`business_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 668820
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Yelp`.`checkin_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`checkin_data` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`checkin_data` (
  `business_id` VARCHAR(50) NULL DEFAULT NULL,
  `date` TEXT NULL DEFAULT NULL,
  `checkin_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`checkin_id`),
  INDEX `checkin_data_business_id_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `checkin_data_business_id`
    FOREIGN KEY (`business_id`)
    REFERENCES `Yelp`.`business_data` (`business_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13356876
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Yelp`.`elite_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`elite_user` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`elite_user` (
  `user_id` VARCHAR(50) NULL DEFAULT NULL,
  `elite_year` TEXT NULL DEFAULT NULL,
  `elite_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`elite_id`),
  INDEX `elite_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `elite_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Yelp`.`user_data` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2278756
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Yelp`.`friends_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`friends_user` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`friends_user` (
  `user_id` VARCHAR(50) NULL DEFAULT NULL,
  `friends_user_id` VARCHAR(50) NULL DEFAULT NULL,
  `friends_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`friends_id`),
  INDEX `user_user_id_idx` (`user_id` ASC, `friends_user_id` ASC) VISIBLE,
  INDEX `friends_friend_user_id_idx` (`friends_user_id` ASC) VISIBLE,
  CONSTRAINT `fk1_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Yelp`.`user_data` (`user_id`),
  CONSTRAINT `fk2_user_id`
    FOREIGN KEY (`friends_user_id`)
    REFERENCES `Yelp`.`user_data` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 105282648
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Yelp`.`hours_business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`hours_business` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`hours_business` (
  `business_id` VARCHAR(50) NULL DEFAULT NULL,
  `Monday` TEXT NULL DEFAULT NULL,
  `Tuesday` TEXT NULL DEFAULT NULL,
  `Wednesday` TEXT NULL DEFAULT NULL,
  `Thursday` TEXT NULL DEFAULT NULL,
  `Friday` TEXT NULL DEFAULT NULL,
  `Saturday` TEXT NULL DEFAULT NULL,
  `Sunday` TEXT NULL DEFAULT NULL,
  `hours_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`hours_id`),
  INDEX `hours_business_id_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `hours_business_id`
    FOREIGN KEY (`business_id`)
    REFERENCES `Yelp`.`business_data` (`business_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 127153
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Yelp`.`review_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`review_data` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`review_data` (
  `review_id` VARCHAR(50) NOT NULL,
  `user_id` VARCHAR(50) NULL DEFAULT NULL,
  `business_id` VARCHAR(50) NULL DEFAULT NULL,
  `stars` BIGINT NULL DEFAULT NULL,
  `useful` BIGINT NULL DEFAULT NULL,
  `funny` BIGINT NULL DEFAULT NULL,
  `cool` BIGINT NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `review_data_user id_idx` (`user_id` ASC) VISIBLE,
  INDEX `review_data_business_id_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `review_data_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `Yelp`.`business_data` (`business_id`),
  CONSTRAINT `review_data_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Yelp`.`user_data` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Yelp`.`tip_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`tip_data` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`tip_data` (
  `user_id` VARCHAR(50) NULL DEFAULT NULL,
  `business_id` VARCHAR(50) NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `compliment_count` BIGINT NULL DEFAULT NULL,
  `tip_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`tip_id`),
  INDEX `tip_data_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `tip_data_business_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `tip_data_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `Yelp`.`business_data` (`business_id`),
  CONSTRAINT `tip_data_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Yelp`.`user_data` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 908916
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Yelp`.`user_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yelp`.`user_data` ;

CREATE TABLE IF NOT EXISTS `Yelp`.`user_data` (
  `user_id` VARCHAR(50) NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `review_count` BIGINT NULL DEFAULT NULL,
  `yelping_since` TEXT NULL DEFAULT NULL,
  `useful` BIGINT NULL DEFAULT NULL,
  `funny` BIGINT NULL DEFAULT NULL,
  `cool` BIGINT NULL DEFAULT NULL,
  `fans` BIGINT NULL DEFAULT NULL,
  `average_stars` DOUBLE NULL DEFAULT NULL,
  `compliment_hot` BIGINT NULL DEFAULT NULL,
  `compliment_more` BIGINT NULL DEFAULT NULL,
  `compliment_profile` BIGINT NULL DEFAULT NULL,
  `compliment_cute` BIGINT NULL DEFAULT NULL,
  `compliment_list` BIGINT NULL DEFAULT NULL,
  `compliment_note` BIGINT NULL DEFAULT NULL,
  `compliment_plain` BIGINT NULL DEFAULT NULL,
  `compliment_cool` BIGINT NULL DEFAULT NULL,
  `compliment_funny` BIGINT NULL DEFAULT NULL,
  `compliment_writer` BIGINT NULL DEFAULT NULL,
  `compliment_photos` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
